# Generated by Django 5.2.3 on 2025-06-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_diaryentry_is_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaryentry',
            options={'verbose_name_plural': 'Diary Entries'},
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
