# Generated by Django 5.2.3 on 2025-06-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_diaryentry_options_diaryentry_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
