# Generated by Django 5.2.3 on 2025-06-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
